# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fd6ac66bddde51bf065902218b8fcfc25857726c2826b8b7bdb6631771ddbf810d6103e4caa485a68e241a72359d983ac100a75985d956e65192ce98adc96e7

test:
  secret_key_base: 9581efbe36f484e2abcde2e7ae7dba073c0be1c0a3723e1de000c84fd39d137f7640c19578600c02739ae148314d3c755a416f1b62f96a20483e8a30660115f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
